CREATE TABLE ANP (
    ANP_ID      BIGINT(20) NOT NULL AUTO_INCREMENT,
    ANP_NAME   VARCHAR(200) NOT NULL,
    ANP_DESCRIPTION  LONGTEXT NOT NULL,
    ANP_PRICE  DECIMAL(15, 2) NOT NULL,
    ANP_IMAGE   LONGTEXT NULL DEFAULT NULL,
    PRIMARY KEY (ANP_ID)
);

CREATE TABLE USER (
    USER_ID      BIGINT(20) NOT NULL AUTO_INCREMENT,
    USER_NAME   VARCHAR(200) NOT NULL,
    USER_LNAME  VARCHAR(200) NOT NULL,
    USER_EMAIL  VARCHAR(200) NOT NULL,
    USER_PASSWORD   VARCHAR(200) NOT NULL,
    PRIMARY KEY (USER_ID)

);

CREATE TABLE PAYMENT (
    PAYMENT_ID      BIGINT(20) NOT NULL AUTO_INCREMENT,
    PAYMENT_TOTAL   VARCHAR(200) NOT NULL,
    PAYMENT_TQUANTITY  VARCHAR(200) NOT NULL,
    USER_ID      BIGINT(20) NOT NULL,
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE TICKET (
    TICKET_ID      BIGINT(20) NOT NULL AUTO_INCREMENT,
    TICKET_BDATE      DATETIME NOT NULL,
    TICKET_TDATE     DATETIME NOT NULL,
    ANP_ID   BIGINT(20) NOT NULL,
    PAYMENT_ID  BIGINT(20) NOT NULL,
    PRIMARY KEY (TICKET_ID),
    FOREIGN KEY (ANP_ID) REFERENCES ANP(ANP_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);
